- src/Microsoft.Dism/DismApi.cs
Add new ThrowIfFail() method to centralize failure detection
#1
> Add new ThrowIfFail() method to centralize failure detection

- src/Microsoft.Dism.Tests/DismCapabilityInfoTest.cs
- src/Microsoft.Dism.Tests/DismCapabilityTest.cs
- src/Microsoft.Dism.Tests/Microsoft.Dism.Tests.csproj
- src/Microsoft.Dism.sln
- src/Microsoft.Dism/DismApi.cs
- src/Microsoft.Dism/DismCapability.cs
- src/Microsoft.Dism/DismCapabilityInfo.cs
- src/Microsoft.Dism/Microsoft.Dism.csproj
- src/Microsoft.Dism/NativeMethods.cs
Provides implementation of missing API
> Capabilities API

- src/Microsoft.Dism.Tests/DismAppxPackageTest.cs
- src/Microsoft.Dism.Tests/Microsoft.Dism.Tests.csproj
- src/Microsoft.Dism/DismApi.cs
- src/Microsoft.Dism/DismAppxPackage.cs
- src/Microsoft.Dism/Microsoft.Dism.csproj
- src/Microsoft.Dism/NativeEnums.cs
- src/Microsoft.Dism/NativeMethods.cs
These were taken from the DISM PowerShell module
@MichalPavlik can you make sure this looks good for you?
Closes #10
> Initial implementation of provisioned appx methods.

- src/Microsoft.Dism.Package/Microsoft.Dism.Package.nuproj
- src/Microsoft.Dism.Tests/DismExceptionTest.cs
- src/Microsoft.Dism.Tests/project.json
- src/Microsoft.Dism/DismApi.cs
- src/Microsoft.Dism/DismException.cs
- src/Microsoft.Dism/ExtensionMethods.cs
- src/Microsoft.Dism/Microsoft.Dism.csproj
- src/Microsoft.Dism/NativeConstants.cs
- src/Microsoft.Dism/NativeStructs.cs
- src/Microsoft.Dism/project.json
I just moved what is needed over to this project.  This makes this assembly stand-alone.
> Remove dependency on Microsoft.Win32Ex

- .build/local/Extensions/AssemblyInfo.props
- src/Microsoft.Dism.Package/Microsoft.Dism.Package.nuproj
- src/Microsoft.Dism.Package/ReleaseNotes.xml
> Update to version 1.6

- Packages.props
- src/Microsoft.Dism.Tests/Base/DismCollectionTest.cs
- src/Microsoft.Dism.Tests/Base/DismStructTest.cs
- src/Microsoft.Dism.Tests/Base/TestBase.cs
- src/Microsoft.Dism.Tests/DismAppxPackageTest.cs
- src/Microsoft.Dism.Tests/DismCapabilityInfoTest.cs
- src/Microsoft.Dism.Tests/DismCapabilityTest.cs
- src/Microsoft.Dism.Tests/DismCustomPropertyTest.cs
- src/Microsoft.Dism.Tests/DismDriverPackageTest.cs
- src/Microsoft.Dism.Tests/DismDriverTest.cs
- src/Microsoft.Dism.Tests/DismFeatureInfoTest.cs
- src/Microsoft.Dism.Tests/DismFeatureTest.cs
- src/Microsoft.Dism.Tests/DismImageInfoTest.cs
- src/Microsoft.Dism.Tests/DismInitializeTest.cs
- src/Microsoft.Dism.Tests/DismMountedImageInfoTest.cs
- src/Microsoft.Dism.Tests/DismPackageInfoTest.cs
- src/Microsoft.Dism.Tests/DismPackageTest.cs
- src/Microsoft.Dism.Tests/DismWimCustomizedInfoTest.cs
- src/Microsoft.Dism.Tests/Microsoft.Dism.Tests.csproj
- src/Microsoft.Dism.Tests/TestWimTemplate.cs
> Generate a test WIM file for functional unit tests.

- src/Microsoft.Dism/DismApi.cs
Add a lock and a boolean to keep track of initialization
> Ensure initialization only happens once

- Microsoft.Dism.sln
- src/Microsoft.Dism.Tests/Base/DismTestBase.cs
- src/Microsoft.Dism.Tests/Base/TestBase.cs
- src/Microsoft.Dism.Tests/CheckImageHealthTest.cs
- src/Microsoft.Dism.Tests/Microsoft.Dism.Tests.csproj
* Add DismTestBase for unit tests that need DismApi to be initialized/shut down
> Add CheckImageHealthTest

- src/Microsoft.Dism.Tests/GetCapabilitiesTest.cs
- src/Microsoft.Dism.Tests/GetImageInfoTest.cs
> Add GetCapabilitiesTest and GetImageInfoTest

- src/Microsoft.Dism.Tests/DismImageInfoTest.cs
Accidentally duplicated by #54
> Remove duplicated test

- src/Microsoft.Dism.Tests/GetPackagesTest.cs
- src/Microsoft.Dism.Tests/GetProvisionedAppxPackagesTest.cs
- src/Microsoft.Dism/NativeEnums.cs
Also add `GetPackagesTest` and improve `GetProvisionedAppxPackagesSimple`
Address #32
>  Add missing DismReleaseType.OnDemandPack

- src/Microsoft.Dism.Tests/ApplyUnattendTest.cs
- src/Microsoft.Dism.Tests/Base/DismInstallWimTestBase.cs
- src/Microsoft.Dism.Tests/Base/TestBase.cs
- src/Microsoft.Dism.Tests/Microsoft.Dism.Tests.csproj
install.wim is the smallest WIM I could find that tests can run against
Addresses #32
> Add WIM that can be used for functional tests

- src/Microsoft.Dism.Tests/DismPackageInfoExTest.cs
- src/Microsoft.Dism.Tests/GetPackageInfoExTest.cs
- src/Microsoft.Dism/DismApi.GetPackageInfoEx.cs
- src/Microsoft.Dism/DismFeatureInfo.cs
- src/Microsoft.Dism/DismPackageInfo.cs
- src/Microsoft.Dism/DismPackageInfoEx.cs
Also converted some fields to auto-properties
> Add support for GetPackageInfoEx

- Directory.Build.props
- Packages.props
- src/Microsoft.Dism.Tests/DismCustomPropertyTest.cs
- src/Microsoft.Dism.Tests/TestWimTemplate.cs
- src/Microsoft.Dism/DismAppxPackage.cs
- src/Microsoft.Dism/DismCustomProperty.cs
- src/Microsoft.Dism/DismDriver.cs
- src/Microsoft.Dism/DismDriverPackage.cs
- src/Microsoft.Dism/DismException.cs
- src/Microsoft.Dism/DismFeature.cs
- src/Microsoft.Dism/DismFeatureInfo.cs
- src/Microsoft.Dism/DismImageInfo.cs
- src/Microsoft.Dism/DismMountedImageInfo.cs
- src/Microsoft.Dism/DismPackage.cs
- src/Microsoft.Dism/DismPackageInfo.cs
- src/Microsoft.Dism/DismPackageInfoEx.cs
- src/Microsoft.Dism/DismWimCustomizedInfo.cs
> Adopt some analyzers

- src/Microsoft.Dism/DismApi.ApplyFfuImage.cs
- src/Microsoft.Dism/DismApi.SplitFfuImage.cs
These APIs are undocumented but I found the usage info from `dism.exe`.
Fixes #79
> Add ApplyFfuImage and SplitFfuImage

- Directory.Build.props
- Directory.Build.targets
- Packages.props
- azure-pipelines.yml
- src/Microsoft.Dism.Tests/GetProvisionedAppxPackagesTest.cs
- src/Microsoft.Dism.Tests/Microsoft.Dism.Tests.csproj
- src/Microsoft.Dism/Microsoft.Dism.csproj
Change how symbols are generated
Update pipeline
Clean up properties
> Minor maintenance

- Directory.Build.props
- dismapi.h
- global.json
- src/Microsoft.Dism/DismApi.AddProvisionedAppxPackage.cs
Since this function was never public, it has changed in the latest release.  It is now part of the public API so it shouldn't change again.
Fixes #87
> Update _DismAddProvisionedAppxPackage method

- src/Microsoft.Dism.Tests/DismExceptionTest.cs
- src/Microsoft.Dism/DismApi.AddPackage.cs
- src/Microsoft.Dism/DismException.cs
- src/Microsoft.Dism/NativeConstants.cs
- src/Microsoft.Dism/Properties/Resources.Designer.cs
- src/Microsoft.Dism/Properties/Resources.resx
Add new exception with message and update documentation.
Fixes #92
> Add friendly exception message when DismAddPackage returns CBS_E_NOT_APPLICABLE

- src/Microsoft.Dism/DismApi.CheckImageHealth.cs
- src/Microsoft.Dism/DismApi.RemoveProvisionedAppxPackage.cs
Was not passing this in correctly from `CheckImageHealth` and `RemoveProvisionedAppxPackage`
Fixes #95
> Pass session to ThrowIfFail

- src/Microsoft.Dism/CallerMemberNameAttribute.cs
> Make CallerMemberNameAttribute internal

- src/Microsoft.Dism.Tests/DismSessionTest.cs
- src/Microsoft.Dism/DismApi.OpenSession.cs
- src/Microsoft.Dism/DismApi.OpenSessionEx.cs
- src/Microsoft.Dism/DismSession.cs
- src/Microsoft.Dism/DismSessionOptions.cs
- src/Microsoft.Dism/DismUtilities.cs
- src/Microsoft.Dism/PublicAPI.Unshipped.txt
> Added the ability to suppress exceptions when a reboot is required

- azure-pipelines.yml
- version.json
Also fix CI build to not rebuild when running tests
> Update version to 2.2

- dismapi.h
- src/Microsoft.Dism/DismApi.AddProvisionedAppxPackage.cs
- src/Microsoft.Dism/NativeEnums.cs
- src/Microsoft.Dism/PublicAPI.Shipped.txt
- src/Microsoft.Dism/PublicAPI.Unshipped.txt
- version.json
> Add StubPackageOption to AddProvisionedAppxPackage

- Packages.props
- azure-pipelines.yml
- src/Microsoft.Dism.Tests/Microsoft.Dism.Tests.csproj
- src/Microsoft.Dism/Microsoft.Dism.csproj
- version.json
* Add code coverage
* Minor cleanup
> Update build logic

- src/Microsoft.Dism/DismApi.GetDriverInfo.cs
- src/Microsoft.Dism/PublicAPI.Unshipped.txt
> Add overload to GetDriverInfo to also get the DismDriverPackage

- src/Microsoft.Dism.Tests/GetRegistryMountPointTest.cs
- src/Microsoft.Dism/DismApi.GetRegistryMountPoint.cs
- src/Microsoft.Dism/NativeEnums.cs
- src/Microsoft.Dism/PublicAPI.Unshipped.txt
Note: this method is only applicable to offline images, so I've tested it locally.
> Added GetRegistryMountPoint

- Directory.Packages.props
- src/Microsoft.Dism.Tests/Microsoft.Dism.Tests.csproj
Remove references to `coverlet.collector` and `Microsoft.NETFramework.ReferenceAssemblies`
> Repo maintenance
